name: mt19937
version: 0.1.0
synopsis: Standard 32-bit Mersenne Twister PRNG, in pure Haskell
description: Please see README.md.
extra-source-files:
- README.md
- CHANGELOG.md
category: Data, Random, Cryptography
tested-with: GHC ==9.8.1, GHC==9.6.4, GHC==9.4.8, GHC==9.2.8
license: MIT
license-file: LICENSE

github: raehik/mt19937-hs
maintainer: Ben Orchard <thefirstmuffinman@gmail.com>
author: Ben Orchard

# raehik's extensions (GHC 9.2; last updated: 2022-10-09)
language: GHC2021
default-extensions:
# syntax that should be default
- LambdaCase
- NoStarIsType

## deriving-related
- DerivingVia # implies DerivingStrategies
- DeriveAnyClass

# features that should be default
- GADTs
- RoleAnnotations

# other features
- DefaultSignatures
- TypeFamilies
- DataKinds

# other syntax
- MagicHash

# useful extensions to know about, but which should be specified on-demand
#
# UndecidableInstances:
#   required for type class wizardry
#   generally only enable if you were expecting to & compilation fails without
# AllowAmbiguousTypes:
#   often goes hand in hand with TypeApplications-heavy code
#   enabling on demand brings attention to the sort of functions to expect
# StarIsType:
#   may need to enable if you're working with old code that uses `Int :: *`

ghc-options:
- -Wall

dependencies:
- base >= 4.16.3.0 && < 4.20 # blaze it
- vector >= 0.13.1.0 && < 0.14

library:
  source-dirs: src
